namespace CPPIADecompiler;

public static class Boilerplate
{
    // Exact full names of known classes and their corresponding prints.
    // the prints are generated by Fingerprint.Of(module, cls) and are used to verify that the decompiled code matches the known generated code.
    static readonly Dictionary<string, string[]> Known = new(StringComparer.Ordinal)
    {
        ["cpp.cppia.HostClasses"] = ["61b6877481a78f1b"],
        ["funkin.ui.debug.charting.ChartEditorLiveInputStyle"] = ["c65cd078885cd1c7"],
        ["funkin.ui.debug.charting.ChartEditorTheme"] = ["32efaa4dab1664e5"],
        ["funkin.ui.debug.stageeditor.StageEditorTheme"] = ["c9155c93f2409f2c"],
        ["haxe._EntryPoint.Lock"] = ["cbfc7844240abd75"],
        ["haxe._EntryPoint.Mutex"] = ["7b037bccd9703eab"],
        ["haxe._EntryPoint.Thread"] = ["60ff2b966cfad813"],
        ["haxe.lang.Iterable"] = ["5e7e0bcd40f0c61c"],
        ["haxe.lang.Iterator"] = ["e395f129ceaf0d6d"],
        ["haxe.Exception"] = ["8ac91879da2d9b80"],
        ["haxe.ValueException"] = ["07b67586d9664e8a"],
        ["haxe.iterators.ArrayIterator"] = ["4afe7c7712bf7e32"]
    };

    public static bool IsKnownName(string fullName) => Known.ContainsKey(fullName);

    public static bool Matches(string fullName, string print) =>
        Known.TryGetValue(fullName, out string[]? prints) && Array.IndexOf(prints, print) >= 0;
}
